PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE COMPONENTS(
COMPONENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME		     VARCHAR(30) NOT NULL,
CALORIES_PER_100_g   FLOAT	 NOT NULL,
TYPE		     VARCHAR(25) NOT NULL
);
INSERT INTO COMPONENTS VALUES(1,'test',1.2299999999999999822,'mieso');
CREATE TABLE DAY_CONSUMPTIONS(
DAY_CONSUMPTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
DATE		   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
CALORIES_SUM	   FLOAT	NOT NULL,
MEAT_CALORIES	   FLOAT,
MILKY_CALORIES	   FLOAT,
WHOLEGRAIN_CALORIES FLOAT,
FRUIT_CALORIES	   FLOAT,
VEGETABLE_CALORIES FLOAT
);
INSERT INTO DAY_CONSUMPTIONS VALUES(1,'2017-07-31 15:59:28',10.0,1.0,2.0,3.0,2.0,2.0);
CREATE TABLE DAY_COMPONENTS(
DAY_COMPONENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
COMPONENT_ID 	 INTEGER NOT NULL,
DATE		 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
WEIGHT		 FLOAT	 NOT NULL,
MEAL		 VARCHAR(15)
);
INSERT INTO DAY_COMPONENTS VALUES(1,1,'2017-07-31 17:01:44',100.0,'Lunch');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('COMPONENTS',1);
INSERT INTO sqlite_sequence VALUES('DAY_CONSUMPTIONS',1);
INSERT INTO sqlite_sequence VALUES('DAY_COMPONENTS',1);
COMMIT;
