PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE FOOD(
ID INT PRIMARY KEY	NOT NULL,
NAME	TEXT		NOT NULL,
CALORIES	REAL	NOT NULL,
TYPE	TEXT,
VITAMINS	TEXT,
WEIGHT	REAL
);
INSERT INTO "FOOD" VALUES(1,'Apple',52.0,'Fruit','C',100.0);
INSERT INTO "FOOD" VALUES(2,'Orange',86.0,'Fruit','C',184.27);
INSERT INTO "FOOD" VALUES(3,'Banana',105.0,'Fruit','C',118.0);
INSERT INTO "FOOD" VALUES(4,'Pear',98.0,'Fruit','C',164.43);
INSERT INTO "FOOD" VALUES(5,'Carrot',52.0,'Vegetable','A',150.0);
INSERT INTO "FOOD" VALUES(6,'Cucumber',7.0,'Vegetable','C',56.7);
INSERT INTO "FOOD" VALUES(7,'Onion',36.0,'Vegetable','C',85.05);
COMMIT;
